name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v14
        with:
          java-version: 11
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt', '**/build.properties') }}
      - name: Run tests
        run: sbt +compile +test scalastyle
